// SPDX-FileCopyrightText: Copyright 2026 The SLSA Authors
// SPDX-License-Identifier: Apache-2.0

package attest

import (
	"errors"
	"testing"

	"github.com/carabiner-dev/attestation"
	sapi "github.com/carabiner-dev/signer/api/v1"
	"github.com/stretchr/testify/require"
)

// fakeEnvelope is a minimal attestation.Envelope for testing the
// verifier's envelope checks.
type fakeEnvelope struct {
	verifyErr    error
	verification attestation.Verification
}

func (f *fakeEnvelope) GetStatement() attestation.Statement       { return nil }
func (f *fakeEnvelope) GetPredicate() attestation.Predicate       { return nil }
func (f *fakeEnvelope) GetSignatures() []attestation.Signature    { return nil }
func (f *fakeEnvelope) GetCertificate() attestation.Certificate   { return nil }
func (f *fakeEnvelope) GetVerification() attestation.Verification { return f.verification }
func (f *fakeEnvelope) Verify(_ ...any) error                     { return f.verifyErr }

// signedBy returns verification data as generated by the collector
// envelopes after a successful cryptographic check.
func signedBy(issuer, san string) attestation.Verification {
	return &sapi.Verification{
		Signature: &sapi.SignatureVerification{
			Verified: true,
			Identities: []*sapi.Identity{{
				Sigstore: &sapi.IdentitySigstore{
					Issuer:   issuer,
					Identity: san,
				},
			}},
		},
	}
}

func TestVerifyEnvelope(t *testing.T) {
	t.Parallel()
	for _, tc := range []struct {
		name    string
		env     attestation.Envelope
		mustErr bool
	}{
		{
			name:    "nil-envelope",
			env:     nil,
			mustErr: true,
		},
		{
			name:    "signature-verification-fails",
			env:     &fakeEnvelope{verifyErr: errors.New("bad signature")},
			mustErr: true,
		},
		{
			// Bare statements return a nil error from Verify but never
			// produce verification data. They must be rejected.
			name:    "unsigned-envelope",
			env:     &fakeEnvelope{},
			mustErr: true,
		},
		{
			name: "unverified-signature",
			env: &fakeEnvelope{verification: &sapi.Verification{
				Signature: &sapi.SignatureVerification{Verified: false},
			}},
			mustErr: true,
		},
		{
			name:    "wrong-identity",
			env:     &fakeEnvelope{verification: signedBy(ExpectedIssuer, "https://github.com/attacker/repo/.github/workflows/fake.yml@refs/heads/main")},
			mustErr: true,
		},
		{
			name:    "wrong-issuer",
			env:     &fakeEnvelope{verification: signedBy("https://accounts.google.com", ExpectedSanPrefix+"refs/heads/main")},
			mustErr: true,
		},
		{
			// The workflow identity ends with whatever reference the
			// user pinned it to: a digest, a tag or a branch.
			name: "workflow-pinned-to-digest",
			env:  &fakeEnvelope{verification: signedBy(ExpectedIssuer, ExpectedSanPrefix+"dea965cdca5e0cb422bf7b2653c9d15f678ad01c")},
		},
		{
			name: "workflow-pinned-to-tag",
			env:  &fakeEnvelope{verification: signedBy(ExpectedIssuer, ExpectedSanPrefix+"refs/tags/v0.1.0")},
		},
		{
			name: "workflow-pinned-to-branch",
			env:  &fakeEnvelope{verification: signedBy(ExpectedIssuer, ExpectedSanPrefix+"refs/heads/main")},
		},
		{
			// A lookalike repository or workflow must not match the prefix
			name:    "lookalike-repository",
			env:     &fakeEnvelope{verification: signedBy(ExpectedIssuer, "https://github.com/slsa-framework/actions-fork/.github/workflows/compute_slsa_source.yml@refs/heads/main")},
			mustErr: true,
		},
		{
			name:    "lookalike-workflow",
			env:     &fakeEnvelope{verification: signedBy(ExpectedIssuer, "https://github.com/slsa-framework/actions/.github/workflows/compute_slsa_source.yml.evil@refs/heads/main")},
			mustErr: true,
		},
		{
			name:    "other-workflow-in-actions-repo",
			env:     &fakeEnvelope{verification: signedBy(ExpectedIssuer, "https://github.com/slsa-framework/actions/.github/workflows/release.yaml@refs/heads/main")},
			mustErr: true,
		},
		{
			// Attestations signed while the actions lived in the
			// source-actions repository are still accepted.
			name: "legacy-source-actions-identity",
			env:  &fakeEnvelope{verification: signedBy(ExpectedIssuer, LegacySourceActionsSan)},
		},
		{
			// Attestations signed before the repository split are
			// still accepted (issue #255).
			name: "legacy-poc-identity",
			env:  &fakeEnvelope{verification: signedBy(ExpectedIssuer, LegacyPocSan)},
		},
		{
			// The legacy identities are matched exactly, other refs
			// of the legacy workflows are not accepted.
			name:    "legacy-workflow-other-ref",
			env:     &fakeEnvelope{verification: signedBy(ExpectedIssuer, "https://github.com/slsa-framework/source-actions/.github/workflows/compute_slsa_source.yml@refs/heads/feature")},
			mustErr: true,
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			err := GetDefaultVerifier().VerifyEnvelope(tc.env)
			if tc.mustErr {
				require.Error(t, err)
				return
			}
			require.NoError(t, err)
		})
	}
}

func TestVerifyEnvelopeCustomIdentity(t *testing.T) {
	t.Parallel()
	custom := NewBndVerifier(VerificationOptions{
		ExpectedIssuer: ExpectedIssuer,
		ExpectedSan:    "https://github.com/example/repo/.github/workflows/sign.yml@refs/heads/main",
	})

	// The pinned identity verifies
	require.NoError(t, custom.VerifyEnvelope(&fakeEnvelope{
		verification: signedBy(ExpectedIssuer, "https://github.com/example/repo/.github/workflows/sign.yml@refs/heads/main"),
	}))

	// ... and without alternates, the default identities don't
	require.Error(t, custom.VerifyEnvelope(&fakeEnvelope{
		verification: signedBy(ExpectedIssuer, ExpectedSanPrefix+"refs/heads/main"),
	}))
	require.Error(t, custom.VerifyEnvelope(&fakeEnvelope{
		verification: signedBy(ExpectedIssuer, LegacySourceActionsSan),
	}))
	require.Error(t, custom.VerifyEnvelope(&fakeEnvelope{
		verification: signedBy(ExpectedIssuer, LegacyPocSan),
	}))
}

func TestVerifyEnvelopeRequiresIssuer(t *testing.T) {
	t.Parallel()
	// Without an issuer, no identity is accepted (fail closed)
	for _, opts := range []VerificationOptions{
		{ExpectedSan: LegacySourceActionsSan},
		{ExpectedSanPrefix: ExpectedSanPrefix},
		{AlternateSans: []string{LegacyPocSan}},
	} {
		verifier := NewBndVerifier(opts)
		require.Empty(t, opts.expectedIdentities())
		require.Error(t, verifier.VerifyEnvelope(&fakeEnvelope{
			verification: signedBy(ExpectedIssuer, LegacySourceActionsSan),
		}))
		require.Error(t, verifier.VerifyEnvelope(&fakeEnvelope{
			verification: signedBy(ExpectedIssuer, ExpectedSanPrefix+"refs/heads/main"),
		}))
	}
}

func TestVerificationOptionsExpectedIdentities(t *testing.T) {
	t.Parallel()
	// The exact SAN takes precedence over the prefix, alternates are added
	ids := (&VerificationOptions{
		ExpectedIssuer:    ExpectedIssuer,
		ExpectedSan:       "https://github.com/example/repo/.github/workflows/sign.yml@refs/heads/main",
		ExpectedSanPrefix: ExpectedSanPrefix,
		AlternateSans:     []string{"", LegacyPocSan},
	}).expectedIdentities()
	require.Len(t, ids, 2)
	require.Equal(t, "https://github.com/example/repo/.github/workflows/sign.yml@refs/heads/main", ids[0].GetSigstore().GetIdentity())
	require.Nil(t, ids[0].GetSigstore().GetIdentityMatch())
	require.Equal(t, LegacyPocSan, ids[1].GetSigstore().GetIdentity())

	// The defaults use the prefix plus the legacy identities
	ids = DefaultVerifierOptions.expectedIdentities()
	require.Len(t, ids, 3)
	require.Empty(t, ids[0].GetSigstore().GetIdentity())
	require.Equal(t, ExpectedSanPrefix, ids[0].GetSigstore().GetIdentityMatch().GetPrefix())
	require.Equal(t, ExpectedIssuer, ids[0].GetSigstore().GetIssuer())
}
